none_str_ = '-'
remove_str_ = 'X'

name_ = 'Name'
due_date_ = 'Due'
priority_ = 'Priority'
picture_ = 'Picture'
money_ = 'Money'
contact_info_ = 'Contact Info'
phone_ = 'Phone'
phone_exp_ = '10 digits'
address_ = 'Address'
street_address_ = 'Street Address'
city_ = 'City'
state_ = 'State'
zip_code_ = 'Zip Code'
created_date_ = 'Created on'

month_ = 'Month'
day_ = 'Day'
year_ = 'Year'

